[package]
name = "prieto-buffers-derive"
version = "1.0.0"
description = "Macro implementation for prieto-buffers"
license = "MIT"
repository = "https://github.com/Jordise2002/prieto-buffers"
categories = ["no-std", "encoding"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "3"
quote = "1"
proc-macro2 = "1"
byteorder = "1.4"