[package]
name = "prieto-buffers"
version = "1.0.0"
description = "No-std minimal overhead serialization library for embedded devices"
license = "MIT"
repository = "https://github.com/Jordise2002/prieto-buffers"
categories = ["no-std", "encoding"]
edition = "2024"

[features]
default = ["derive", "struct-len-size-0", "array-len-size-0"]
derive = ["dep:prieto-buffers-derive"]
std = []

struct-len-size-0 = [] #Struct size fits with type, max fields in a struct: 32
struct-len-size-1 = [] #Struct size occupies one byte, max fields in a struct: 255
struct-len-size-2 = [] #Struct size occupies two bytes, max fields in a struct: 65535
struct-len-size-4 = [] #Struct size occupies four bytes, max fields in a struct: 4294967296

array-len-size-0 = [] #Array size fits with type, max elements in an array: 32
array-len-size-1 = [] #Array size occupies one byte, max elements in an array: 255
array-len-size-2 = [] #Array size occupies two bytes, max elements in an array: 65535
array-len-size-4 = [] #Array size occupies four bytes, max elements in an array: 4294967296

[dependencies]
prieto-buffers-derive = { version = "1", optional = true }